name: Publish PyPI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install 3.12

      - name: Install the project
        run: uv sync --all-extras --dev
      
      - name: Build package
        run: uv build

      - name: Publish package
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.UV_PUBLISH_TOKEN }}
        run: uv publish
